### ISSUE TITLE
-bash: ctrld: command not found on Ubiquiti Dream Router

### ISSUE THREAD

**Issue by candroid-man** [Control-D-Inc/ctrld#154]
I installed ctrld via the installation script:
```
sh -c 'sh -c "$(curl -sL https://api.controld.com/dl)"'
```
I wasn't able to successfully use the tool, as the command claims to not exist.

I also tried navigating to the installation folder, and some directory that doesn't exist that I found from #132:
```
cd /data/controld
```
```
cd /jffs/controld/
```
This resulted in the same issue. 

I also tried running:
```
sudo ./ctrld run
```
I also tried re-running the installation script which reinstalled the service, so it is apparently on my router and it shows it's working in the ControlD dashboard, however I want to configure it further via the CLI tool.

There weren't any additional instructions during the setup on how to use the tool, so most likely I'm just dumb. When I had NextDNS on the router all I had to do was enter the command and it worked out of the root directory.

**Comment by yegors** [comment]
The install script tells you where the binary is downloaded, you execute it from that directory, which is `/data/controld` - since this directly is not in the system path, you must run the binary from an absolute location. 

You also don't want to use `run` mode.

If you're using Control D, you create a Ubiqiti device, and it gives you an exact install command, you run that, once and close terminal. There is nothing else for you to do.
